#!/usr/bin/env bash
# Deploy MockERC20 + A402VaultSettlement onto a running Anvil, then write
# .env.evm.generated at the repo root so other tools can pick it up.
#
# Prereqs:
#   - Anvil is already running at $RPC_URL (default http://127.0.0.1:8545)
#   - foundryup has installed forge
#   - forge install foundry-rs/forge-std --no-commit has been run once
#
# Anvil's default deterministic account #0 is used as the deployer + submitter.
# That account has unlimited ETH on Anvil so eth_sendTransaction works without
# a separate signer — matching what the enclave's EVM submitter expects in dev.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
EVM_DIR="$ROOT/chains/ethereum"
DEPLOYMENT_JSON="$EVM_DIR/deployments/local.json"

RPC_URL="${A402_EVM_RPC_URL:-http://127.0.0.1:8545}"

# Anvil deterministic account #0
DEPLOYER_PRIVATE_KEY="${DEPLOYER_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}"
DEPLOYER_ADDRESS="${DEPLOYER_ADDRESS:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}"

cd "$EVM_DIR"

if [[ ! -d "lib/forge-std" ]]; then
    echo "lib/forge-std missing — installing forge-std..."
    forge install foundry-rs/forge-std
fi

echo "Deploying via forge script to $RPC_URL ..."
PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY" \
EVM_SUBMITTER="$DEPLOYER_ADDRESS" \
    forge script script/Deploy.s.sol:Deploy \
    --rpc-url "$RPC_URL" \
    --broadcast \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    -vvv

if [[ ! -f "$DEPLOYMENT_JSON" ]]; then
    echo "deployment json not produced at $DEPLOYMENT_JSON" >&2
    exit 1
fi

USDC=$(jq -r .mockUsdc "$DEPLOYMENT_JSON")
VAULT=$(jq -r .vaultSettlement "$DEPLOYMENT_JSON")
ASC_MANAGER=$(jq -r .ascManager "$DEPLOYMENT_JSON")
ASC_VAULT_EOA=$(jq -r .ascVaultEoa "$DEPLOYMENT_JSON")
SCHNORR_VERIFIER=$(jq -r .schnorrVerifier "$DEPLOYMENT_JSON")

ENV_FILE="$ROOT/.env.evm.generated"
cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/evm/bootstrap.sh — do not edit by hand.
A402_EVM_RPC_URL=$RPC_URL
A402_EVM_SETTLEMENT_CONTRACT=$VAULT
A402_EVM_SUBMITTER=$DEPLOYER_ADDRESS
A402_EVM_ASSET=$USDC
A402_EVM_ASC_MANAGER=$ASC_MANAGER
A402_EVM_ASC_VAULT_EOA=$ASC_VAULT_EOA
A402_EVM_SCHNORR_VERIFIER=$SCHNORR_VERIFIER
EOF

echo
echo "Deployment complete."
echo "  Mock USDC:          $USDC"
echo "  Vault Settlement:   $VAULT"
echo "  Schnorr Verifier:   $SCHNORR_VERIFIER"
echo "  ASC Manager:        $ASC_MANAGER"
echo "  ASC Vault EOA:      $ASC_VAULT_EOA"
echo "  Submitter:          $DEPLOYER_ADDRESS"
echo "  Generated env:      $ENV_FILE"
